[General]
cacheConfig = false

[js]
cachePath = WEBROOT/cache_js/

[jquery-combined.js]
files[] = jquery-1.7.2.js
files[] = jquery-ui-1.8.20.custom.min.js
files[] = bootstrap-transition.js
files[] = bootstrap-alert.js
files[] = bootstrap-collapse.js
files[] = bootstrap-tooltip.js
files[] = bootstrap-popover.js
files[] = bootstrap-dropdown.js
files[] = jquery.autosave.js
files[] = jquery.validate.js
files[] = pv.js
filters[] = JsMinFilter

[css]
cachePath = WEBROOT/cache_css/

[default.css]
files[] = jquery-ui-1.8.20.custom.css
files[] = bootstrap.css
files[] = style.css
files[] = bootstrap-responsive.css
files[] = pv.css
files[] = compatibility_hacks.css
files[] = style-responsive.css
; filters[] = CssMinFilter