[Cron1]
; Initial Cron that sent three types of email at once. Evoked EmailShell.php main() method. Deprecated
; * 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email > /dev/null 2>&1 
 * 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendNewSadrEmail > /dev/null 2>&1 
 * 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendNewPqmpEmail > /dev/null 2>&1 
 * 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendNewSadrFollowupEmail > /dev/null 2>&1 

[Cron2]
; Initial Cron that sent three submit emails at once. Evoked EmailShell.php sendSubmitEmail() method. Deprecated
; * 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendSubmitEmail >/dev/null 2>&1 	
* 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendSubmitSadrEmail >/dev/null 2>&1 	
* 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendSubmitPqmpEmail >/dev/null 2>&1 	
* 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendSubmitSadrFollowupEmail >/dev/null 2>&1 	

[Cron3]
; Sends emails to users who forget their passwords
* 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendForgotEmail >/dev/null 2>&1 

[Cron4]
; Send Messages 
* 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendMessages >/dev/null 2>&1 

[Cron5]
; Send Reports
* 	* 	* 	* 	* 	/home/intellis/public_html/demo/pv/lib/Cake/Console/cake -app /home/intellis/public_html/demo/pv/app email sendReports >/dev/null 2>&1 