<?php
App::uses('AppController', 'Controller');
/**
 * Users Controller
 *
 * @property User $User
 */
class UsersController extends AppController {
	public $components = array('Search.Prg');
	public $paginate = array();
    public $presetVars = array(
        array('field' => 'username', 'type' => 'value'),
        array('field' => 'name', 'type' => 'value'),
        array('field' => 'email', 'type' => 'value'),
        array('field' => 'start_date', 'type' => 'value'),
        array('field' => 'end_date', 'type' => 'value'),
    );

	public function beforeFilter() {
		parent::beforeFilter();
		// remove initDb
		$this->Auth->allow('register', 'login', 'forgotPassword', 'resetPassword', 'logout', 'initDB');
	}


	public function login() {
		if ($this->Session->read('Auth.User')) {
			$this->Session->setFlash('You are logged in!', 'flash_success');
			$this->redirect('/', null, false);
		}
		if ($this->request->is('post')) {
			if ($this->Auth->login()) {
				// $this->redirect($this->Auth->redirect());
				$this->Session->setFlash('You are now logged into the website.', 'flash_success');
				if ($this->Auth->user('is_admin')) {
					return $this->redirect(array(
						'controller' => 'pages',
						'action' => 'dashboard',
						'admin' => true
					));
				} else {
					$this->redirect('/');
				}
			} else {
				$this->Session->setFlash('Your username or password was incorrect.', 'flash_error');
			}
		}
	}

	public function admin_login() {
		if ($this->Session->read('Auth.User')) {
			$this->Session->setFlash('You are logged in!', 'flash_success');
			$this->redirect(array('controller' => 'pages', 'action' => 'dashboard',	'admin' => true  ), null, false);
		}

		if ($this->request->is('post')) {
			if ($this->Auth->login()) {
				if ($this->Auth->user('is_admin')) {
					return $this->redirect(array(
						'controller' => 'pages',
						'action' => 'dashboard',
						'admin' => true
					));
				} else {
					$this->Session->setFlash('You are not registered as an administrator.', 'flash_error');
					$this->redirect($this->Auth->logout());
				}
			} else {
				$this->Session->setFlash('Your username or password was incorrect.', 'flash_error');
			}
		}
	}

	public function logout() {
		$this->Session->setFlash('Good-Bye','flash_info');
		$this->redirect($this->Auth->logout());
	}

	public function changePassword() {
		if (!$this->Auth->User('id')) {
			$this->Session->setFlash(__('You are NOT logged in! Please login to change your password'), 'flash_info');
			$this->redirect('/', null, false);
		}
		if ($this->request->is('post')  || $this->request->is('put')) {
			$this->request->data['User']['id'] = $this->Session->read('Auth.User.id');
			unset($this->User->validate['email']);
			$this->User->create();
			if ($this->User->save($this->request->data, array('fieldlist' => array('old_password', 'password', 'confirm_password')))) {
				$this->Session->setFlash(__('The password has been changed'), 'flash_success');
				$this->redirect(array('action' => 'changePassword'));
			} else {
				$this->Session->setFlash(__('The password could not be changed.'), 'flash_error');
				// pr($this->request->data);
			}
		}
		$this->User->Designation->recursive = -1;
		$this->set('designation', $this->User->Designation->findById($this->Auth->user('designation_id'), array('name')));
		$this->User->County->recursive = -1;
		$this->set('county', $this->User->County->findById($this->Auth->user('county_id'), array('county_name')));
	}

	public function forgotPassword() {
		if ($this->Auth->user('id')) {
			$this->Session->setFlash(__('You are logged in! Please logout to request password change'), 'flash_info');
			$this->redirect('/', null, false);
		}
		if ($this->request->is('post')) {
			$user = $this->User->find('first', array('conditions' => array('User.email' => $this->request->data['User']['email'])));
			if ($user) {
				$this->User->id = $user['User']['id'];
				$this->User->saveField('forgot_password', 1);
				$this->Session->setFlash(__('A new password has been sent to the requested address.'), 'flash_success');
				$this->redirect('/');
			} else {
				$this->Session->setFlash(__('Could not verify your email address.'), 'flash_error');
			}
		}
	}

	public function resetPassword($id) {
		//confirm user id hash for authenticity
		//reset password to autogenerated string (e.g use luhn checksum (5) of id with simple replace e.g 2=>eh)
		$this->User->id = $this->User->Luhn_Verify($id, 7);
		if (!$this->User->exists()) {
			$this->Session->setFlash(__('Could not verify the user ID. Please ensure the ID is correct.'), 'flash_error');
			$this->redirect('/');
		} else {
			// $this->User->save('forgot_password', 0);
			$user = $this->User->read(null);
			if ($user['User']['forgot_password'] != 2) {
				$this->Session->setFlash(__('The password has not been reset.'), 'flash_error');
				$this->redirect('/');
			}
			if($this->User->save(
								array('User' => array('password' =>  $id, 'confirm_password' => $id))
								, array('fieldList' =>  array('password', 'confirm_password'))
			)) {
				$this->Session->setFlash(__('The password has been reset. You may now login using your new password.'), 'flash_success');
			} else {
				$this->Session->setFlash(__('The password has not been reset. Please contact PPB for further help'), 'flash_error');
			}
			$this->redirect('/');
		}
	}

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->User->recursive = 0;
		$this->set('users', $this->paginate());
	}

    public function admin_index() {
        $this->Prg->commonProcess();
		if (!empty($this->passedArgs['start_date']) || !empty($this->passedArgs['end_date'])) $this->passedArgs['range'] = true;
		if (isset($this->passedArgs['pages']) && !empty($this->passedArgs['pages'])) $this->paginate['limit'] = $this->passedArgs['pages'];
        else $this->paginate['limit'] = 20;
		$criteria = $this->User->parseCriteria($this->passedArgs);
        $this->paginate['conditions'] = $criteria;
        $this->paginate['order'] = array('User.created' => 'desc');
 		$this->User->recursive = -1;

		$this->set('users', $this->paginate());
    }

	public function admin_user_activate($id = null) {
		if ($id) {
			$this->User->id = $id;
			if ($this->User->saveField('is_active', 1)) {
				return $this->redirect(array( 'controller' => 'users', 'action' => 'index', 'admin' => true ));
			}
		}
	}
/**
 * view method
 *
 * @param string $id
 * @return void
 */
	public function view($id = null) {
		$this->User->id = $id;
		if (!$this->User->exists()) {
			throw new NotFoundException(__('Invalid user'));
		}
		$this->set('user', $this->User->read(null, $id));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->User->create();
			if ($this->User->save($this->request->data)) {
				$this->Session->setFlash(__('The user has been saved'));
				$this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('You could not be registered. Please try again.'), 'flash_error');
			}
		}
		$groups = $this->User->Group->find('list');
		$this->set(compact('groups'));
	}

	public function admin_add() {
		if ($this->request->is('post')) {
			$this->User->create();
			if ($this->User->save($this->request->data)) {
				$this->Session->setFlash(__('The user has been saved'), 'flash_success');
				$this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('You could not be registered. Please try again.'), 'flash_error');
			}
		}
		$groups = $this->User->Group->find('list');
		$this->set(compact('groups'));
		$designations = $this->User->Designation->find('list');
		$this->set(compact('designations'));
		$counties = $this->User->County->find('list');
		$this->set(compact('counties'));
	}

/**
 * register method
 *
 * @return void
 */
	public function register() {
		if ($this->request->is('post')) {
			$this->User->create();
			$this->request->data['User']['group_id'] = 3;
			if (empty($this->data['User']['bot_stop']) && $this->User->save($this->request->data)) {
				$id = $this->User->id;
				$this->request->data['User'] = array_merge($this->request->data['User'], array('id' => $id));
				$this->Auth->login($this->request->data['User']);
				$this->Session->setFlash(__('You have successfully registered'), 'flash_success');
				$this->redirect('/');
			} else {
				$this->Session->setFlash(__('The user could not be saved. Please, try again.'), 'flash_error');
			}
		}
		$groups = $this->User->Group->find('list');
		$this->set(compact('groups'));
		$designations = $this->User->Designation->find('list');
		$this->set(compact('designations'));
		$counties = $this->User->County->find('list');
		$this->set(compact('counties'));
	}

/**
 * edit method
 *
 * @param string $id
 * @return void
 */
	public function edit($id = null) {
		$this->User->id = $id;
		if (!$this->User->exists()) {
			$this->Session->setFlash(__('The user does not exist.'), 'flash_info');
			$this->redirect('/', null, false);
		}
		if ($this->Auth->User('id') != $id) {
			$this->Session->setFlash(__('You do not have permission to edit this user!'), 'flash_info');
			$this->redirect('/', null, false);
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			// $this->request->data['User']['group_id'] = 2;
			unset($this->User->validate['username']);
			unset($this->User->validate['password']);
			unset($this->User->validate['confirm_password']);
			if ($this->User->save($this->request->data)) {
				$this->Session->setFlash(__('Your details have been updated'), 'flash_success');
				$this->redirect(array('action' => 'changePassword', $this->id));
			} else {
				$this->Session->setFlash(__('The user could not be saved. Please, try again.'), 'flash_error');
			}
		} else {
			$this->request->data = $this->User->read(null, $id);
		}
		$designations = $this->User->Designation->find('list');
		$this->set(compact('designations'));
		$counties = $this->User->County->find('list');
		$this->set(compact('counties'));
	}

	public function admin_edit($id = null) {
		$this->User->id = $id;
		if (!$this->User->exists()) {
			$this->Session->setFlash(__('The user '.$id.' does not exist.'), 'flash_error');
			$this->redirect('/', null, false);
		}

		if ($this->request->is('post') || $this->request->is('put')) {
			// unset($this->User->validate['username']);
			// unset($this->User->validate['password']);
			// unset($this->User->validate['confirm_password']);
			if ($this->User->save($this->request->data)) {
				$this->Session->setFlash(__('Your details have been updated'), 'flash_success');
				$this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The user could not be saved. Please, try again.'), 'flash_error');
			}
		} else {
			$this->request->data = $this->User->read(null, $id);
			unset($this->request->data['User']['password']);
			unset($this->request->data['User']['confirm_password']);
		}
		$groups = $this->User->Group->find('list');
		$this->set(compact('groups'));
		$designations = $this->User->Designation->find('list');
		$this->set(compact('designations'));
		$counties = $this->User->County->find('list');
		$this->set(compact('counties'));
	}

/**
 * delete method
 *
 * @param string $id
 * @return void
 */
	public function delete($id = null) {
		if (!$this->request->is('post')) {
			throw new MethodNotAllowedException();
		}
		$this->User->id = $id;
		if (!$this->User->exists()) {
			throw new NotFoundException(__('Invalid user'));
		}
		if ($this->User->delete()) {
			$this->Session->setFlash(__('User deleted'));
			$this->redirect(array('action' => 'index'));
		}
		$this->Session->setFlash(__('User was not deleted'));
		$this->redirect(array('action' => 'index'));
	}

	public function admin_delete($id = null) {
		if (!$this->request->is('post')) {
			throw new MethodNotAllowedException();
		}
		$this->User->id = $id;
		if (!$this->User->exists()) {
			throw new NotFoundException(__('Invalid user'));
		}
		if ($this->User->delete()) {
			$this->Session->setFlash(__('User deleted'));
			$this->redirect(array('action' => 'index'));
		}
		$this->Session->setFlash(__('User was not deleted'));
		$this->redirect(array('action' => 'index'));
	}

	/**/public function initDB() {
		$group = $this->User->Group;
		//Allow admins to everything
		$group->id = 1;
		$this->Acl->allow($group, 'controllers');

		//Allow managers to some
		$group->id = 2;
		$this->Acl->deny($group, 'controllers');
		$this->Acl->allow($group, 'controllers/Sadrs');
		$this->Acl->allow($group, 'controllers/Aefis');
		$this->Acl->allow($group, 'controllers/SadrFollowups');
		$this->Acl->allow($group, 'controllers/Pqmps');
		$this->Acl->allow($group, 'controllers/Attachments');
		$this->Acl->allow($group, 'controllers/Counties');
		$this->Acl->allow($group, 'controllers/Countries');
		$this->Acl->allow($group, 'controllers/Designations');
		$this->Acl->allow($group, 'controllers/Doses');
		$this->Acl->allow($group, 'controllers/DrugDictionaries');
		$this->Acl->allow($group, 'controllers/FacilityCodes');
		$this->Acl->allow($group, 'controllers/Feedbacks');
		$this->Acl->allow($group, 'controllers/Frequencies');
		$this->Acl->allow($group, 'controllers/HelpInfos');
		$this->Acl->allow($group, 'controllers/Messages');
		$this->Acl->allow($group, 'controllers/Routes');
		$this->Acl->allow($group, 'controllers/SadrListOfDrugs');
		$this->Acl->allow($group, 'controllers/WhoDrugs');
		$this->Acl->allow($group, 'controllers/Pages');
		$this->Acl->allow($group, 'controllers/Users/changePassword');
		$this->Acl->allow($group, 'controllers/Users/edit');
		$this->Acl->allow($group, 'controllers/Users/admin_index');
		$this->Acl->allow($group, 'controllers/Users/admin_add');
		$this->Acl->deny($group, 'controllers/Acl');
		$this->Acl->allow($group, 'controllers/Groups/admin_index');

		//Allow reporters to some
		$group->id = 3;
		$this->Acl->deny($group, 'controllers');
		$this->Acl->allow($group, 'controllers/Sadrs/sadrIndex');
		$this->Acl->allow($group, 'controllers/Sadrs/institutionCodes');
		$this->Acl->allow($group, 'controllers/Aefis/aefiIndex');
		$this->Acl->allow($group, 'controllers/Aefis/institutionCodes');
		$this->Acl->allow($group, 'controllers/SadrFollowups/sadrIndex');
		$this->Acl->allow($group, 'controllers/SadrFollowups/followupIndex');
		$this->Acl->allow($group, 'controllers/Pqmps/pqmpIndex');
		$this->Acl->allow($group, 'controllers/Users/changePassword');
		$this->Acl->allow($group, 'controllers/Users/edit');

		//Allow institution administrators to some
		$group->id = 4;
		$this->Acl->deny($group, 'controllers');
		$this->Acl->allow($group, 'controllers/Sadrs/sadrIndex');
		$this->Acl->allow($group, 'controllers/Sadrs/institutionCodes');
		$this->Acl->allow($group, 'controllers/Aefis/aefiIndex');
		$this->Acl->allow($group, 'controllers/Aefis/institutionCodes');
		$this->Acl->allow($group, 'controllers/SadrFollowups/sadrIndex');
		$this->Acl->allow($group, 'controllers/SadrFollowups/followupIndex');
		$this->Acl->allow($group, 'controllers/Pqmps/pqmpIndex');
		$this->Acl->allow($group, 'controllers/Users/changePassword');
		$this->Acl->allow($group, 'controllers/Users/edit');

		echo "all done";
		exit;
	}
}
